### ISSUE TITLE
Entertainer: Cannot Stat Migrate without Image Designer Skills

### ISSUE THREAD

**Issue by Tenkata** [kinshi/tarkin_scripts#93]
Category: Entertainer
Reproducibility: Always
Severity: Low
Priority: Normal
Summary: Stat Migration without Image Designer Skills is greyed out. Skills are possibly required to Image Design

Description: I attempted to Stat Migrate another player in Coronet with no boxes in Image Designer (I only had Novice Entertainer as far as image designing skills were concerned. I was unable to stat migrate him or myself. Being inside a Image Designer Tent did not appear to make a difference. Image designer works as it should on Basilisk Nothing related to Image Designer bugs was located on Mantis. The person i Image Desgined said he could Stat Migrate himself, however i do not know if he was an Image Designer or not.

Steps To Reproduce:
1. Attempt to Image design a player as an Entertainer with Entertainer X444. 
2. Move to the Advanced section of the Image Designer Window.

The Stat Migration Button should be greyed out and unclickable.

Attached Files: 

![screenshot0010](https://cloud.githubusercontent.com/assets/1145639/7645212/593f1f7e-fa66-11e4-9de4-2997d870153e.jpg)

**Comment by kinshi** [comment]
Stat migration functions for others using normal ID methods still require use of the ID tent.

The Tarkin method of self-stat migration only supports using the stat-migration button on the character sheer and requires no ID skills at all and cannot be performed on others.

 Please re-verify using self-only stat-migration from the player's character sheet, not using ID skills

**Comment by Tenkata** [comment]
Stat Migration using the character sheet currently functions, I did not understand how the system worked. Issue exists between keyboard and chair.

**Comment by Magni828** [comment]
Ah. A layer 8 issue. :)
