### ISSUE TITLE
Travel: Teleporter to high end content results in possible server crash.

### ISSUE THREAD

**Issue by Tenkata** [kinshi/tarkin_scripts#94]
Category: Travel
Reproducibility: Always 
Severity: Major
Priority: Normal
Summary: When used, the Coronet teleporter to the Lord Nyax Bunker appears to cause a server crash. 
Description: I went to the Coronet Teleporter to the Lord Nyax Bunker and when clicking on it I go into the loading screen as normal. In the middle of loading, the server appears to crash. I am currently not sure if the server does in fact crash as nobody else is online.

Attached Files: None

**Comment by kinshi** [comment]
I think I know what this is, Emu had changed some pointer handling, and I thought I had updated all the teleporter screenplays but may have missed one,

Verified as a bug in the screenplay

**Comment by kinshi** [comment]
Fixed by commit 5140c45abbe2ba665fa6814c1f130bd02902d418 - fix is live for the Correllia SP screenplay.

I still need to apply the fixes to other teleporters in the Zephyr Network. I will leave this open until I finalize the other screenplays with this fix.

**Comment by kinshi** [comment]
Fixed, and merged
